### ISSUE TITLE
ValueRequiredException (v1.1, SonarQube 6.7)

### ISSUE THREAD

**Issue by alixwar** [ofields/sonar-android#26]
Hi,

I'm seeing this problem in my multi-module Gradle project when analysing with SonarQube.

My setup:
- Gradle 4.6
- Gradle Android Plugin 3.1.0
- SonarQube 6.7 (Android plugin 1.1)

```
0:41:43.080 [Task worker for ':' Thread 2] ERROR o.s.p.a.lint.AndroidLintProcessor - Exception reading /builds/MYPROJECT/build/reports/lint-results-debug.xml
org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(entry=, inline=true, data=false, name=, type=void, required=true, empty=true) on field 'issues' java.util.List org.sonar.plugins.android.lint.AndroidLintProcessor$LintIssues.issues for class org.sonar.plugins.android.lint.AndroidLintProcessor$LintIssues at line 2
	at org.simpleframework.xml.core.Composite.validate(Composite.java:644) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:449) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Composite.read(Composite.java:201) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Composite.read(Composite.java:148) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Persister.read(Persister.java:625) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Persister.read(Persister.java:606) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Persister.read(Persister.java:584) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Persister.read(Persister.java:543) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Persister.read(Persister.java:521) ~[simple-xml-2.7.1.jar:na]
	at org.simpleframework.xml.core.Persister.read(Persister.java:426) ~[simple-xml-2.7.1.jar:na]
	at org.sonar.plugins.android.lint.AndroidLintProcessor.process(AndroidLintProcessor.java:57) ~[sonar-android-plugin-1.1.jar:na]
	at org.sonar.plugins.android.lint.AndroidLintSensor.analyse(AndroidLintSensor.java:53) [sonar-android-plugin-1.1.jar:na]
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:281) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111) [sonar-scanner-engine-shaded-6.7.jar:na]
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63) [sonar-scanner-api-batch3409968465006685507.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-api-2.9.0.887.jar:na]
	at com.sun.proxy.$Proxy95.execute(Unknown Source) [na:na]
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233) [sonar-scanner-api-2.9.0.887.jar:na]
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-api-2.9.0.887.jar:na]
	at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:99) [sonarqube-gradle-plugin-2.6.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73) [gradle-base-services-4.6.jar:4.6]
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43) [gradle-core-4.6.jar:4.6]
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597) [gradle-core-4.6.jar:4.6]
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98) [gradle-core-4.6.jar:4.6]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) [gradle-base-services-4.6.jar:4.6]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) [gradle-base-services-4.6.jar:4.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) [gradle-base-services-4.6.jar:4.6]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by alixwar** [comment]
Here is the lint XML (obfuscated): https://pastebin.com/GpnYBQhG
